osx_image: xcode10.1
language: objective-c
#before_install: pod update
script: xcodebuild clean build -verbose -project Akku/Akku.xcodeproj -scheme Akku CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
